name: Build libgcc

on:
  push:
    branches:
      - 'trunk'
  workflow_dispatch:

jobs:
  prepare:
    name: Compute release tag
    runs-on: ubuntu-latest
    outputs:
      tag_date: ${{ steps.set.outputs.tag_date }}
    steps:
      - name: Compute timestamp
        id: set
        run: echo "tag_date=$(date -u +'%Y%m%dT%H%M%SZ')" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    strategy:
      matrix:
        target_arch: [i386, i686, x86_64, arm, aarch64, loongarch64, loongarch64-softfloat, riscv64, riscv64-softfloat, m68k, ppc64]

    name: Build libgcc for ${{matrix.target_arch}}
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git autoconf automake wget bison flex texinfo file

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Extrapolate target triplet
        run: |
          case "${{matrix.target_arch}}" in \
            arm) \
              echo "arm-none-eabi" >target-triplet ;; \
            loongarch64-softfloat) \
              echo "loongarch64-elf" >target-triplet ;; \
            riscv64-softfloat) \
              echo "riscv64-elf" >target-triplet ;; \
            ppc64) \
              echo "powerpc64-linux-gnu" >target-triplet ;; \
            *) \
              echo "${{matrix.target_arch}}-elf" >target-triplet ;; \
          esac

      - name: Build the toolchain
        run: |
          CFLAGS_FOR_TARGET=""; \
          case "${{matrix.target_arch}}" in \
            loongarch64-softfloat) \
              CFLAGS_FOR_TARGET="$CFLAGS_FOR_TARGET -mabi=lp64s -mfpu=none -msimd=none";; \
            riscv64-softfloat) \
              CFLAGS_FOR_TARGET="$CFLAGS_FOR_TARGET -march=rv64imac_zicsr_zifencei -mabi=lp64";; \
            ppc64) \
              CFLAGS_FOR_TARGET="$CFLAGS_FOR_TARGET -m64 -mno-altivec -mno-vsx";; \
          esac; \
          case "${{matrix.target_arch}}" in \
            riscv64*) \
              CFLAGS_FOR_TARGET="$CFLAGS_FOR_TARGET -mno-relax";; \
          esac; \
          case "${{matrix.target_arch}}" in \
            ppc64) \
              ADDITIONAL_GCC_CONFIGURE_FLAGS="--disable-threads --disable-shared";; \
          esac; \
          CFLAGS_FOR_TARGET="-O2 -pipe -fPIC -Wa,--noexecstack $CFLAGS_FOR_TARGET" TARGET="$(cat target-triplet)" ADDITIONAL_GCC_CONFIGURE_FLAGS="$ADDITIONAL_GCC_CONFIGURE_FLAGS" ./make_toolchain.sh

      - name: Copy libgcc.a
        run: cp toolchain/output/lib/gcc/*/*/libgcc.a ./libgcc-${{matrix.target_arch}}.a

      - name: Copy extra libgcc.a's
        run: |
          case "${{matrix.target_arch}}" in \
            x86_64) \
              cp toolchain/output/lib/gcc/*/*/no-red-zone/libgcc.a ./libgcc-x86_64-no-red-zone.a ;; \
          esac

      - name: Upload libgcc artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgcc-${{ matrix.target_arch }}
          path: libgcc-*.a
          if-no-files-found: error

  release:
    needs: [prepare, build]
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download all libgcc artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          pattern: libgcc-*
          merge-multiple: true

      - name: Read toolchain versions
        run: |
          grep -o 'GCCVERSION=.*$' make_toolchain.sh >> $GITHUB_ENV
          grep -o 'BINUTILSVERSION=.*$' make_toolchain.sh >> $GITHUB_ENV

      - name: Tag new release
        run: |
          git tag ${{ needs.prepare.outputs.tag_date }}
          git push --tags

      - name: Create new release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ needs.prepare.outputs.tag_date }}
          tag_name: ${{ needs.prepare.outputs.tag_date }}
          body: |
            This build is based on:
              - GNU Binutils ${{ env.BINUTILSVERSION }}
              - GCC ${{ env.GCCVERSION }}
          files: |
            COPYING*
            artifacts/*.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
